### PR TITLE
3rd analysis

### PR DESCRIPTION
**Pull request by peterdesmet**
Since September 2014 GBIF adopted the policy that datasets should be published under a [standard license](http://www.gbif.org/terms/licences), encouraging publishers to choose CC0. One of the ways this is encouraged, is by enforcing publishers to choose one of the 3 standard licenses when publishing a dataset through the IPT (since [IPT 2.2](https://github.com/gbif/ipt/wiki/IPTReleaseNotes22.wiki), released in March 2015).

I was curious what affect this has had on all GBIF-mediated data, so I reran the analysis of all licenses used by GBIF data publishers. As this is the 3rd run in 3 years, we're starting to see some yearly trends to (I should probably adopt the analysis to more easily compare these). For the previous runs, see the screenshots below or:
- 1st run (2013-11-22): http://peterdesmet.com/posts/analyzing-gbif-data-licenses.html
- 2nd run (2014-10-28): https://github.com/Datafable/gbif-data-licenses/pull/45
## Scope of this run
- Datasets: 15,260 (includes non-occurrence datasets)
- New licenses (I had to [manually interpret](https://github.com/Datafable/gbif-data-licenses/blob/master/guidelines.md)) since last run: 152

The results of the analysis are included in this repository, but below are screenshots per year (in reverse chronological order).
## Results

It's encouraging to see that things are improving, especially in the number of occurrences (thanks to the massive dataset [eBird choosing for CC0](http://www.gbif.org/dataset/4fa7b334-ce0d-4e88-aaae-2e0c138d049e)) and that when choosing a standard license, [most datasets are published under CC0](https://github.com/Datafable/gbif-data-licenses/blob/master/data/generated/standard-license-data.csv) (68% of standard licensed datasets). Most datasets however (84%) are still published under no license (78%) or a non-standard license (6%), so GBIF and its community still have a lot of work ahead to enforce standard-license use.

### CODE REVIEW

**Comment by peterdesmet** [comment]
This 3rd analysis is now versioned as a release: https://github.com/Datafable/gbif-data-licenses/releases/tag/analysis-3

**Comment by kcopas** [comment]
Hey, Peter—in some ways, it's great to see you running this one more time, as it will provide a very up-to-date baseline for work now underway between the Secretariat and GBIF's national participants. 

We don't anticipate complete this comprehensive review until February 2016, but when we do, all publishers who are able to will have assigned their datasets with machine-readable licences comparable to those currently used. More to follow...

**Comment by qgroom** [comment]
Regarding the results from 2015: do you count datasets with no observations? There seem like quite a large number these days and I wonder if people are taking their data off GBIF rather than choosing a licence. However, I believe GBIF keeps the dataset metadata to avoid breaking links from previous acknowledgements.

**Comment by kcopas** [comment]
Can't say how Datafable are counting, but GBIF's count is across all four
dataset types: metadata-only, checklist, occurrence and sampling-event.
Checklists account for the majority, due to Pangaea (7,035) and Scratchpads
(835, and steadily increasing).

For the record, you will not have seen occurrence datasets disappearing due
to upcoming licensing changes. The biggest reason is that the changes
aren't fully implemented on GBIF.org yet (though they are enforced in the
latest version of the IPT). We continue to work on this front, and both the
progress and responses are quite positive thus far, with only a few notable
exceptions (which we still hope to work out).

=====
*Kyle Copas*
Weysesgade 43
2100 Copenhagen Ø
(+45) 28 75 14 75 | skype kylecopas

**Comment by peterdesmet** [comment]
Hi Quentin,

We analyzed all datasets (i.e. the 4 types mentioned by Kyle). Of course, the stats for occurrences are for datasets with occurrences only.

I don't know if and how many occurrence datasets have 0 records, but you can search for it yourself in https://github.com/Datafable/gbif-data-licenses/blob/master/data/generated/datasets-annotated.csv I'm on my phone, so I can't currently open the file. :-)

**Pull request merged**
